"""§M2 / §M3 — draft-simulation backtest of five fixed strategies against the ADP null.

Pre-registered in EDA_PLAN6.md §M2/§M3.  EVERYTHING below the "FIXED" banner was fixed
before any strategy was evaluated and no strategy was added after seeing results.

League (the owner's, 10-team frame): 10 teams, snake, PPR, starters
1 QB / 2 RB / 2 WR / 1 TE / 2 FLEX(RB,WR) / 1 DST.  DST is out of scope and is assigned
identically to every team, so the draft is 14 rounds of QB/RB/WR/TE = 140 picks.

FIXED — opponent noise model
  Each opponent team t draws a private board  v_{t,i} = ADP_i + eps_{t,i},
  eps ~ N(0, stdev_i) with stdev_i the FFC across-draft SD of player i's draft slot.
  Rationale: the observed dispersion of a player's draft position across drafts is
  generated by variation across drafters, so a per-drafter perturbation with that SD is
  the generative model that reproduces it.  Calibration is CHECKED (realized simulated SD
  of draft slot vs the FFC stdev) and reported, not tuned.
  Positional need constraints: cap 2 QB and 2 TE per team; no second QB/TE until the
  team's mandatory slots (1 QB, 1 TE, 2 RB, 2 WR, 2 FLEX from RB/WR) can still be met;
  hard force-fill when remaining picks equal remaining mandatory slots.

FIXED — strategies (S0 is the null)
  S0 best available by ADP
  S1 best available by our model board (LOSO theta*; see note below)
  S2 RB-first (RB with the first two picks, then best available by ADP)
  S3 zero-RB (no RB before round 5, then best available by ADP)
  S4 elite-TE (a TE within the first three rounds, then best available by ADP)
  S5 VORP-greedy (maximise marginal expected starting-lineup value at every pick)

  S1 note, stated because it bounds what S1 can show: the project's RB board is
  market-anchored (REPORT §23: neither RB arm was adopted, board_value = m(ADP)), so the
  RB ordering is ADP's.  S1's only deviation from S0 is therefore the WR top-30
  re-ordering by LOSO theta* (results/loso_predictions.csv), applied as a permutation of
  the modelled WRs across the ADP slots they occupy.  All other players keep ADP order.
  theta* is leave-one-season-out, so nothing from season y is used to draft season y.

  S5 note: E[season total | pos, ADP] and the replacement levels R_p come from the
  leave-one-season-out isotonic curve (results/sectionM_adp_value_curve.csv) and from
  replacement levels averaged over the other nine seasons.  No season-y realisation.

FIXED — scoring (§M3)
  Weekly optimal starting lineup on realised weekly PPR; a player with no game that week
  cannot be started.  Reported for weeks 1-14 (fantasy regular season), 15-17 (playoffs)
  and 1-17.  Bench depth is therefore valuable automatically.

FIXED — inference
  N = 200 simulated drafts per (season, slot), common random numbers across strategies.
  d_s = per-season mean (S_k - S0); Diebold-Mariano t on 10 season clusters, t(9).
  BH q = 0.10 across the five comparisons.  This is a NEW declared family; {H5,I3}, {K},
  {L} and {L-EXT} are not reopened.

Outputs: results/strategy_backtest.csv, results/strategy_by_slot.csv,
         results/strategy_distribution.csv, results/sim_calibration.csv
Rerun: python3 scripts/29_sectionM_draftsim.py
"""
import sys, os, time
import numpy as np
import pandas as pd
from scipy import stats

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sectionM_common as C

ROOT = C.ROOT
YEARS = C.YEARS
# The 10-team league is the pre-registered primary.  SECTIONM_FRAME=12 reruns the whole
# simulation in a 12-team league as a declared family = 0 frame sensitivity for §M4(4);
# it uses 12 rounds because the FFC board (146 QB/RB/WR/TE rows in 2022) cannot fill
# 12 x 14 = 168 picks.  Outputs are suffixed _12team and never overwrite the primary.
FRAME = int(os.environ.get("SECTIONM_FRAME", "10"))
NTEAM, NROUND, NSIM = (10, 14, 200) if FRAME == 10 else (12, 12, 200)
SUF = ("" if FRAME == 10 else "_12team") + ("" if os.environ.get("SECTIONM_S5REP","real")=="real" else "_s5exp")
POSI = {"QB": 0, "RB": 1, "WR": 2, "TE": 3}
STRATS = ["S0", "S1", "S2", "S3", "S4", "S5"]

# ---------------------------------------------------------------- data
print("loading ...", flush=True)
wk = C.load_weekly()
panel, _, _ = C.build_panel(wk)
avc = pd.read_csv(f"{ROOT}/results/sectionM_adp_value_curve.csv")
rep = pd.read_csv(f"{ROOT}/results/replacement_levels.csv")
repF = rep[rep.frame == FRAME]
loso_wr = pd.read_csv(f"{ROOT}/results/loso_predictions.csv")

# LOSO replacement levels (mean over the other nine seasons), for S5 only.
# SECTIONM_S5REP=exp is a family = 0 DIAGNOSTIC (see sectionM_notes.md): it replaces the
# realized order-statistic replacement with the (D+1)-th best value on the *expected*
# board, putting S5's objective and its baseline on the same scale.  Not a strategy.
S5REP = os.environ.get("SECTIONM_S5REP", "real")
_brk = pd.read_csv(f"{ROOT}/results/sectionM_replacement_bracket.csv")
_brk = _brk[_brk.frame == FRAME]
R_loso = {}
for y in YEARS:
    for p in C.POSNS:
        if S5REP == "exp":
            R_loso[(y, p)] = _brk[(_brk.pos == p) & (_brk.year != y)].R_exp.mean()
        else:
            R_loso[(y, p)] = repF[(repF.pos == p) & (repF.year != y)].R_static_total.mean()


def build_season(y):
    b = panel[panel.year == y].copy().sort_values("adp").reset_index(drop=True)
    b = b.head(160).reset_index(drop=True)          # deep enough for 140 picks
    n = len(b)
    adp = b.adp.values.astype(float)
    sd = b.stdev.values.astype(float)
    pos = np.array([POSI[p] for p in b.pos.values])
    # ---- our boards ----
    rank_S0 = np.argsort(adp, kind="stable")
    # S1: permute the modelled WRs across the ADP slots they occupy, by LOSO theta*
    val = adp.copy()
    lw = loso_wr[loso_wr.year == y]
    idx = {pid: i for i, pid in enumerate(b.pid.values)}
    ii = [idx[g] for g in lw.gsis_id.values if g in idx]
    th = np.array([t for g, t in zip(lw.gsis_id.values, lw.theta_star.values) if g in idx])
    if len(ii) > 1:
        slots = np.sort(adp[ii])                     # the ADP slots those WRs occupy
        order = np.argsort(-th)                      # best model value gets the best slot
        newv = np.empty(len(ii))
        newv[order] = slots
        val[ii] = newv
    rank_S1 = np.argsort(val, kind="stable")
    # ---- S5 inputs: LOSO expected season totals ----
    a = avc[avc.year == y].set_index("pid").E_total
    Ev = np.array([a.get(p, np.nan) for p in b.pid.values])
    Ev = np.where(np.isnan(Ev), np.nanmin(Ev), Ev)
    # ---- weekly realised points ----
    m = C.weekly_matrix(wk, y, list(b.pid.values)).values.astype(float)
    m = np.nan_to_num(m, nan=np.nan)
    return dict(y=y, n=n, adp=adp, sd=sd, pos=pos, rank_S0=rank_S0, rank_S1=rank_S1,
                Ev=Ev, wkm=m, pid=b.pid.values, name=b.name.values)


SEASON = {y: build_season(y) for y in YEARS}
for y in YEARS:
    print(f"  {y}: {SEASON[y]['n']} board players, "
          f"pos mix {np.bincount(SEASON[y]['pos'], minlength=4)}")

# ---------------------------------------------------------------- draft engine
MAXQB, MAXTE = 2, 2
# mandatory: 1 QB, 1 TE, 2 RB, 2 WR, 2 FLEX(RB/WR)


def unmet(cnt):
    """remaining mandatory picks given a roster count vector [QB,RB,WR,TE]"""
    q = max(0, 1 - cnt[0]); t = max(0, 1 - cnt[3])
    r = max(0, 2 - cnt[1]); w = max(0, 2 - cnt[2])
    flex = max(0, 6 - (min(cnt[1], 2) + min(cnt[2], 2) + max(0, cnt[1] - 2) + max(0, cnt[2] - 2)))
    return q, r, w, t, flex


def legal_mask(cnt, picks_left):
    """boolean over the 4 positions"""
    ok = np.ones(4, bool)
    if cnt[0] >= MAXQB:
        ok[0] = False
    if cnt[3] >= MAXTE:
        ok[3] = False
    q, r, w, t, flex = unmet(cnt)
    need = q + r + w + t + flex
    if need >= picks_left:                     # force-fill mandatory slots only
        ok[:] = False
        if q:
            ok[0] = True
        if t:
            ok[3] = True
        if r or flex:
            ok[1] = True
        if w or flex:
            ok[2] = True
        if not ok.any():
            ok[:] = True
    else:                                      # no 2nd QB/TE while mandatory unmet
        if cnt[0] >= 1 and (q + r + w + t + flex) > 0:
            ok[0] = False
        if cnt[3] >= 1 and (q + r + w + t + flex) > 0:
            ok[3] = False
    return ok


def opp_pick(order, ptr, taken, pos, cnt, picks_left):
    """ptr may only advance past players who are TAKEN (a monotone property).  A player
    skipped because of a temporary positional-need constraint must remain reachable, so
    the constraint scan starts at ptr and does not persist."""
    while ptr < len(order) and taken[order[ptr]]:
        ptr += 1
    ok = legal_mask(cnt, picks_left)
    j = ptr
    while j < len(order):
        p = order[j]
        if not taken[p] and ok[pos[p]]:
            return p, ptr
        j += 1
    return order[ptr], ptr


def our_pick(S, order, taken, pos, cnt, rnd, picks_left, Ev, Rrep, roster):
    ok = legal_mask(cnt, picks_left)
    if S == "S2" and rnd <= 2:                 # RB with the first two picks
        if (~taken & (pos == 1)).any():
            ok[:] = False; ok[1] = True
    if S == "S3" and rnd <= 4:                 # no RB before round 5
        if (~taken & (pos != 1) & ok[pos]).any():
            ok[1] = False
    if S == "S4" and rnd == 3 and cnt[3] == 0:  # a TE inside the first three rounds
        if (~taken & (pos == 3)).any():
            ok[:] = False; ok[3] = True
    if S == "S5":
        cand = [p for p in order if not taken[p] and ok[pos[p]]][:60]
        if not cand:
            cand = [p for p in order if not taken[p]][:60]
        base = lineup_value(Ev, pos, roster, Rrep)
        best, bi = -1e18, cand[0]
        for p in cand:
            v = lineup_value(Ev, pos, roster + [p], Rrep) - base
            if v > best:
                best, bi = v, p
        return bi
    for p in order:
        if not taken[p] and ok[pos[p]]:
            return p
    for p in order:
        if not taken[p]:
            return p
    return -1


def lineup_value(Ev, pos, roster, Rrep):
    """Expected starting-lineup value of a roster.  Every slot is worth
    max(assigned player, replacement): an unfilled slot takes replacement, and a slot is
    never *forced* to start a sub-replacement player, because a freely available
    replacement-level body can be started instead.  Without the max() the valuer charges
    a negative marginal value for drafting any below-replacement player, which makes the
    greedy refuse whole positions -- see sectionM_notes.md."""
    v = {k: sorted([Ev[p] for p in roster if pos[p] == k], reverse=True) for k in range(4)}
    tot = 0.0
    tot += max(v[0][0], Rrep[0]) if v[0] else Rrep[0]
    tot += max(v[3][0], Rrep[3]) if v[3] else Rrep[3]
    for k, nreq in ((1, 2), (2, 2)):
        got = v[k][:nreq]
        tot += sum(max(x, Rrep[k]) for x in got) + (nreq - len(got)) * Rrep[k]
    Rf = (Rrep[1] + Rrep[2]) / 2
    rest = sorted(v[1][2:] + v[2][2:], reverse=True)[:2]
    tot += sum(max(x, Rf) for x in rest) + (2 - len(rest)) * Rf
    return tot


def score_roster(wkm, pos, roster, w0, w1):
    """weekly optimal lineup 1QB/2RB/2WR/1TE/2FLEX over weeks [w0, w1] inclusive."""
    M = wkm[roster][:, w0 - 1:w1]
    P = pos[roster]
    NEG = -1e9
    out = 0.0
    byp = {k: np.where(P == k)[0] for k in range(4)}
    A = {}
    for k in range(4):
        X = M[byp[k]] if len(byp[k]) else np.zeros((0, M.shape[1]))
        X = np.where(np.isnan(X), NEG, X)
        A[k] = -np.sort(-X, axis=0) if len(X) else X
    def take(k, n):
        X = A[k]
        got = X[:n] if len(X) >= n else np.vstack([X, np.full((n - len(X), M.shape[1]), NEG)])
        rest = X[n:] if len(X) > n else X[:0]
        return got, rest
    qb, _ = take(0, 1); rb, rbr = take(1, 2); wrp, wrr = take(2, 2); te, _ = take(3, 1)
    starters = np.vstack([qb, rb, wrp, te])
    flexpool = np.vstack([rbr, wrr]) if (len(rbr) + len(wrr)) else np.zeros((0, M.shape[1]))
    if len(flexpool):
        flexpool = -np.sort(-flexpool, axis=0)
    fl = flexpool[:2] if len(flexpool) >= 2 else np.vstack(
        [flexpool, np.full((2 - len(flexpool), M.shape[1]), NEG)])
    allst = np.vstack([starters, fl])
    allst = np.where(allst <= NEG / 2, 0.0, allst)
    return float(allst.sum())


def score_static(wkm, pos, roster):
    """DIAGNOSTIC ONLY (family = 0): season totals of the ex-post best 8 starters, i.e.
    the same roster scored as if the lineup were set once for the year.  Contrasting this
    with score_roster isolates how much of a strategy's result is bench/availability."""
    T = np.nan_to_num(wkm[roster], nan=0.0).sum(axis=1)
    P = pos[roster]
    v = {k: sorted(T[P == k], reverse=True) for k in range(4)}
    tot = (v[0][0] if v[0] else 0) + (v[3][0] if v[3] else 0)
    tot += sum(v[1][:2]) + sum(v[2][:2])
    tot += sum(sorted(v[1][2:] + v[2][2:], reverse=True)[:2])
    return float(tot)


# ---------------------------------------------------------------- run
recs, calib = [], []
t0 = time.time()
for y in YEARS:
    S = SEASON[y]
    n, pos, adp, sd = S["n"], S["pos"], S["adp"], S["sd"]
    Rrep = np.array([R_loso[(y, p)] for p in ["QB", "RB", "WR", "TE"]])
    slot_of = np.empty(NTEAM * NROUND, int)
    for r in range(NROUND):
        seq = list(range(NTEAM)) if r % 2 == 0 else list(range(NTEAM))[::-1]
        slot_of[r * NTEAM:(r + 1) * NTEAM] = seq
    drafted_slot = {}
    for myslot in range(NTEAM):
        for sim in range(NSIM):
            rng = np.random.default_rng(1_000_000 * y + 1000 * myslot + sim)
            eps = rng.normal(0, 1, size=(NTEAM, n)) * sd[None, :]
            boards = np.argsort(adp[None, :] + eps, axis=1)
            for st in STRATS:
                taken = np.zeros(n, bool)
                cnt = np.zeros((NTEAM, 4), int)
                rosters = [[] for _ in range(NTEAM)]
                ptr = np.zeros(NTEAM, int)
                for k in range(NTEAM * NROUND):
                    t = slot_of[k]
                    rnd = k // NTEAM + 1
                    left = NROUND - rnd + 1
                    if t == myslot:
                        order = S["rank_S1"] if st == "S1" else S["rank_S0"]
                        p = our_pick(st, order, taken, pos, cnt[t], rnd, left,
                                     S["Ev"], Rrep, rosters[t])
                    else:
                        p, j = opp_pick(boards[t], ptr[t], taken, pos, cnt[t], left)
                        ptr[t] = j
                    taken[p] = True
                    cnt[t][pos[p]] += 1
                    rosters[t].append(p)
                    if st == "S0" and sim < 20:
                        drafted_slot.setdefault(p, []).append(k + 1)
                sc = {}
                for t in range(NTEAM):
                    r14 = score_roster(S["wkm"], pos, rosters[t], 1, 14)
                    r17 = score_roster(S["wkm"], pos, rosters[t], 15, 17)
                    sc[t] = (r14, r17)
                mine = sc[myslot]
                ranks14 = 1 + sum(1 for t in range(NTEAM) if sc[t][0] > mine[0])
                cm = cnt[myslot]
                recs.append(dict(year=y, slot=myslot + 1, sim=sim, strat=st,
                                 pts14=mine[0], pts17=mine[1], pts_all=mine[0] + mine[1],
                                 pts_static=score_static(S["wkm"], pos, rosters[myslot]),
                                 nQB=cm[0], nRB=cm[1], nWR=cm[2], nTE=cm[3],
                                 rank14=ranks14, playoff=int(ranks14 <= (4 if NTEAM == 10 else 5)),
                                 champ=int(ranks14 == 1),
                                 opp_mean14=np.mean([sc[t][0] for t in range(NTEAM) if t != myslot])))
    for p, v in drafted_slot.items():
        calib.append(dict(year=y, pid=S["pid"][p], name=S["name"][p], pos=p,
                          adp=adp[p], ffc_stdev=sd[p], sim_mean=np.mean(v),
                          sim_sd=np.std(v, ddof=1) if len(v) > 1 else np.nan, n=len(v)))
    print(f"  {y} done  {time.time()-t0:.0f}s", flush=True)

R = pd.DataFrame(recs)
R.to_csv(f"{ROOT}/results/strategy_distribution{SUF}.csv", index=False)
cal = pd.DataFrame(calib)
cal.to_csv(f"{ROOT}/results/sim_calibration{SUF}.csv", index=False)

print("\n=== opponent noise calibration (S0 sims, first 20 per slot) ===")
c = cal[cal.adp <= 140]
print(f"  n players {len(c)}   mean FFC stdev {c.ffc_stdev.mean():.2f}   "
      f"mean simulated SD of draft slot {c.sim_sd.mean():.2f}")
print(f"  corr(FFC stdev, sim SD) = {c[['ffc_stdev','sim_sd']].corr().iloc[0,1]:.3f}")
print(f"  mean |sim_mean - adp| = {(c.sim_mean - c.adp).abs().mean():.2f}")

# ---------------------------------------------------------------- §M2 inference
def dm_table(metric):
    rows = []
    piv = R.pivot_table(index=["year", "slot", "sim"], columns="strat", values=metric)
    for st in STRATS[1:]:
        d = (piv[st] - piv["S0"]).groupby(level="year").mean()
        a = d.values
        se = a.std(ddof=1) / np.sqrt(len(a))
        t = a.mean() / se
        rows.append(dict(metric=metric, strat=st, mean_diff=a.mean(), se=se, t=t,
                         p=2 * (1 - stats.t.cdf(abs(t), len(a) - 1)),
                         ci_lo=a.mean() - 2.262 * se, ci_hi=a.mean() + 2.262 * se,
                         mde=2.802 * se, seasons_positive=int((a > 0).sum())))
    out = pd.DataFrame(rows).sort_values("p")
    out["bh_thresh"] = 0.10 * np.arange(1, len(out) + 1) / len(out)
    out["reject"] = out.p <= out.bh_thresh
    return out


bt = pd.concat([dm_table("pts14"), dm_table("pts17"), dm_table("pts_all"),
                dm_table("pts_static")], ignore_index=True)
bt["family"] = np.where(bt.metric == "pts14", 1, 0)   # pts14 is the declared §M family
bt.to_csv(f"{ROOT}/results/strategy_backtest{SUF}.csv", index=False)
print("\n=== §M2 strategy backtest vs S0 (DM clustered by season, t(9), BH q=0.10) ===")
for m in ("pts14", "pts17", "pts_all"):
    print(f"\n-- {m} --")
    print(bt[bt.metric == m].round(3).to_string(index=False))

print("\n=== mean levels and full distribution, weeks 1-14 ===")
g = R.groupby("strat").agg(mean=("pts14", "mean"), sd=("pts14", "std"),
                           p10=("pts14", lambda s: s.quantile(.10)),
                           p50=("pts14", "median"),
                           p90=("pts14", lambda s: s.quantile(.90)),
                           mean_rank=("rank14", "mean"),
                           P_playoff=("playoff", "mean"), P_champ=("champ", "mean"))
print(g.round(3).to_string())

print("\n=== across-slot spread: mean pts14 by draft slot ===")
bs = R.pivot_table(index="slot", columns="strat", values="pts14")
print(bs.round(1).to_string())
print("\n-- difference vs S0 by slot --")
print(bs.sub(bs["S0"], axis=0).round(1).to_string())
bs2 = R.pivot_table(index="slot", columns="strat", values="playoff")
print("\n=== P(top-4 of 10, weeks 1-14) by draft slot ===")
print(bs2.round(3).to_string())
sl = R.groupby(["strat", "slot"]).agg(pts14=("pts14", "mean"), playoff=("playoff", "mean"),
                                      champ=("champ", "mean"), rank14=("rank14", "mean")).reset_index()
sl.to_csv(f"{ROOT}/results/strategy_by_slot{SUF}.csv", index=False)
print(f"\ntotal runtime {time.time()-t0:.0f}s")
